begin;

-- Name corrections from 'Full Digital Doctors List (Jul-26)'
update doctors set name_ar = 'د. سراج ابو النجا', updated_at = now() where slug = 'dr-seraj-aboalnaja';
update doctors set name_en = 'Dr. Mohamed Arab', updated_at = now() where slug = 'dr-mohamad-arab';
update doctors set name_ar = 'د. اميرة التاودي', updated_at = now() where slug = 'dr-amira-eltawdy';
update doctors set name_ar = 'د. سعاد مندورة', updated_at = now() where slug = 'dr-soad-mandoura';
update doctors set name_ar = 'د. احمد امام', updated_at = now() where slug = 'dr-ahmad-imam';
update doctors set name_ar = 'د. احمد الشاعر', updated_at = now() where slug = 'dr-ahmed-alshaer';
update doctors set name_ar = 'د. دينا خوندنه', updated_at = now() where slug = 'dr-dena-khawandanah';
update doctors set name_ar = 'د. مريم اليريمي', updated_at = now() where slug = 'dr-maryam-alyarimi';
update doctors set name_ar = 'د. محمد ابو الحسن', updated_at = now() where slug = 'dr-mohamed-abu-elhasan';
update doctors set name_ar = 'د. عبدالرحمن باحكيم', updated_at = now() where slug = 'dr-abdullah-bahakim';
update doctors set name_ar = 'د. احمد حشيش', updated_at = now() where slug = 'dr-ahmed-hashish';
update doctors set name_ar = 'د. احمد زمي', updated_at = now() where slug = 'dr-ahmed-zmi';
update doctors set name_en = 'Dr. Hossam Alamoodi', updated_at = now() where slug = 'dr-hossam-alamoodi';
update doctors set name_en = 'Dr. Ibrahim Alnouri', updated_at = now() where slug = 'dr-ibrahim-alnoury';
update doctors set name_ar = 'د. مازن مرداد', updated_at = now() where slug = 'dr-mazin-merdad';
update doctors set name_ar = 'د. محمد زهران', updated_at = now() where slug = 'dr-mohamed-zahran';
update doctors set name_ar = 'د. وائل عبدالكافي', updated_at = now() where slug = 'dr-wael-abdelkafy';
update doctors set name_ar = 'د. عبدالله خفاجي', updated_at = now() where slug = 'dr-abdullah-khafagy';
update doctors set name_ar = 'د. افنان ابو علوا', updated_at = now() where slug = 'dr-afnan-aboalwa';
update doctors set name_ar = 'د. ذكرى بازرعة', updated_at = now() where slug = 'dr-dekra-bazarah';
update doctors set name_en = 'Dr. Essam Alghamdi', updated_at = now() where slug = 'dr-essam-alghmadi';
update doctors set name_ar = 'د. ابراهيم القرني', updated_at = now() where slug = 'dr-ibraheem-algarni';
update doctors set name_ar = 'د. اسلام ابو المجد', updated_at = now() where slug = 'dr-islam-abouelmagd';
update doctors set name_ar = 'د. رانية حريري', updated_at = now() where slug = 'dr-rania-harere';
update doctors set name_ar = 'د. ابراهيم بالبيد', updated_at = now() where slug = 'dr-ibrahim-balubaid';
update doctors set name_en = 'Dr. Mohamed Alfawaz', name_ar = 'د. محمد الفواز', updated_at = now() where slug = 'dr-mohamed-alfawaz';
update doctors set name_ar = 'د. سالم بازرعه', updated_at = now() where slug = 'dr-salem-bazaraah';
update doctors set name_ar = 'د. ياسر خياط', updated_at = now() where slug = 'dr-yasir-khayat';
update doctors set name_ar = 'د. مهند صافيه', updated_at = now() where slug = 'dr-muhannad-safiyah';
update doctors set name_en = 'Dr. Ahmed Alzahrani', name_ar = 'د. احمد الزهراني', updated_at = now() where slug = 'dr-ahmed-alzahrani';
update doctors set name_ar = 'د. براءة تطواني', updated_at = now() where slug = 'dr-baraah-tatwany';
update doctors set name_en = 'Dr. Mohamed Abbas', updated_at = now() where slug = 'dr-mohamed-abbass';
update doctors set name_ar = 'د. ايمان عبيد', updated_at = now() where slug = 'dr-eman-obaid';
update doctors set name_en = 'Dr. Mohammed Alsobki', updated_at = now() where slug = 'dr-mohammed-alsobki';
update doctors set name_en = 'Dr. Mansoor Radwi', name_ar = 'د. منصور رضوي', updated_at = now() where slug = 'dr-mansoor-radwi';
update doctors set name_ar = 'د. اشرف وارسي', updated_at = now() where slug = 'dr-ashraf-warsi';
update doctors set name_en = 'Dr. Abdulaziz Alhumoud', updated_at = now() where slug = 'dr-abdulaziz-alhumoud';
update doctors set name_en = 'Dr. Mohammed Omar', updated_at = now() where slug = 'dr-mohammed-omar';
update doctors set name_en = 'Dr. Walaa Aldabbagh', name_ar = 'د. ولاء الدباغ', updated_at = now() where slug = 'dr-walaa-aldabbagh';
update doctors set name_en = 'Dr. Ahmed Basndwah', name_ar = 'د. احمد باسندوه', updated_at = now() where slug = 'dr-ahmed-basndwah';
update doctors set name_ar = 'د. اياد فيزو', updated_at = now() where slug = 'dr-eyad-faizo';
update doctors set name_en = 'Dr. Seraj Makkawi', updated_at = now() where slug = 'dr-seraj-makkawi';
update doctors set name_ar = 'امال الانديجاني', updated_at = now() where slug = 'dr-amal-alandejani';
update doctors set name_ar = 'د. اضواء خضري', updated_at = now() where slug = 'dr-adhwaa-khudhary';
update doctors set name_ar = 'د. احمد الوزان', updated_at = now() where slug = 'dr-ahmed-alwazzan';
update doctors set name_en = 'Dr. Lila Aissawi', name_ar = 'د. ليلى عيسوي', updated_at = now() where slug = 'dr-laila-aissawi';
update doctors set name_ar = 'د. نداء بهكلي', updated_at = now() where slug = 'dr-nedaa-bahkali';
update doctors set name_ar = 'د. اسامة باجوه', updated_at = now() where slug = 'dr-osama-bajouh';
update doctors set name_en = 'Dr. Souzan Alkafy', updated_at = now() where slug = 'dr-souzan-al-kafy';
update doctors set name_ar = 'د. وائل عواد', updated_at = now() where slug = 'dr-wael-auwad';
update doctors set name_en = 'Dr. Albaraa Alqassimi', name_ar = 'د. البراء القاسمي', updated_at = now() where slug = 'dr-albaraa-alqassimi';
update doctors set name_ar = 'د. عزيز البلوي', updated_at = now() where slug = 'dr-aziz-albalawi';
update doctors set name_ar = 'د. غفران ابو داوود', updated_at = now() where slug = 'dr-ghufran-abudawood';
update doctors set name_ar = 'د. هاني اصلان', updated_at = now() where slug = 'dr-hani-aslan';
update doctors set name_ar = 'د. لجين ادريس', updated_at = now() where slug = 'dr-lujain-idriss';
update doctors set name_en = 'Dr. Nawaf Almarzouki', name_ar = 'د. نواف المرزوقي', updated_at = now() where slug = 'dr-nawaf-almarzouki';
update doctors set name_ar = 'د. ريان الشريف', updated_at = now() where slug = 'dr-rayan-alsharief';
update doctors set name_ar = 'د. لينا رفه', updated_at = now() where slug = 'dr-prof-lina-raffa';
update doctors set name_ar = 'د. ايمن اوليا', updated_at = now() where slug = 'dr-ayman-awlia';
update doctors set name_ar = 'د. فايق صواف', updated_at = now() where slug = 'dr-faeg-sawaf';
update doctors set name_ar = 'د. حمزة العوفي', updated_at = now() where slug = 'dr-hamza-alofi';
update doctors set name_ar = 'د. محمد عبدالقادر', updated_at = now() where slug = 'dr-mohammed-abdelkader';
update doctors set name_ar = 'د. محمد عطية', updated_at = now() where slug = 'dr-mohammed-attiah';
update doctors set name_ar = 'د. وائل مجيب', updated_at = now() where slug = 'dr-wael-mojeeb';
update doctors set name_en = 'Dr. Fayez Felemban', updated_at = now() where slug = 'dr-fayez-felemban';
update doctors set name_en = 'Dr. Khalid Alsahhar', name_ar = 'د. خالد السحار', updated_at = now() where slug = 'dr-khalid-alsahhar';
update doctors set name_ar = 'د. عبدالله المغربي', updated_at = now() where slug = 'dr-abdullah-almaghraby';
update doctors set name_ar = 'د. احمد بامقا', updated_at = now() where slug = 'dr-ahmed-bamaga';
update doctors set name_en = 'Dr. Ibrahim Alharbi', name_ar = 'د. ابراهيم الحربي', updated_at = now() where slug = 'dr-ibrahim-alharbi';
update doctors set name_ar = 'د. محمد ايوب', updated_at = now() where slug = 'dr-mohammed-ayoub';
update doctors set name_ar = 'د. ندى كلكتاوي', updated_at = now() where slug = 'dr-nada-kalakattawi';
update doctors set name_ar = 'د. ام سلمى احمد', updated_at = now() where slug = 'dr-omsalamah-ahmed';
update doctors set name_ar = 'د. اسامة باوزير', updated_at = now() where slug = 'dr-osama-bawazeer';
update doctors set name_ar = 'د. تركي الاحمدي', updated_at = now() where slug = 'dr-turki-alahmadi';
update doctors set name_en = 'Dr. Nouf Alzahrani', updated_at = now() where slug = 'dr-nouf-alzahrani';
update doctors set name_ar = 'د. عادل السلمي', updated_at = now() where slug = 'dr-adil-alsulami';
update doctors set name_ar = 'د. فهد عيسى', updated_at = now() where slug = 'dr-fahad-essa';
update doctors set name_ar = 'د. فارس الحجيلي', updated_at = now() where slug = 'dr-faris-alhejaili';
update doctors set name_ar = 'د. سماهر هاشم', updated_at = now() where slug = 'dr-samaher-hashim';
update doctors set name_ar = 'د. حامد مدني', updated_at = now() where slug = 'dr-hamid-madani';
update doctors set name_ar = 'د. عنان خطاب', updated_at = now() where slug = 'dr-anan-khattab';
update doctors set name_en = 'Dr. Laila Salamah', updated_at = now() where slug = 'dr-laila-salamah';
update doctors set name_en = 'Dr. Abdulmajeed Alghamdi', name_ar = 'د. عبدالمجيد الغامدي', updated_at = now() where slug = 'dr-abdulmajeed-alghamdi';
update doctors set name_en = 'Dr. Mohamed Torky', updated_at = now() where slug = 'dr-mohmed-torky';
update doctors set name_en = 'Prof. Ashraf Abosamra', name_ar = 'بروفيسور. اشرف ابو سمره', updated_at = now() where slug = 'dr-prof-ashraf-abosamra';
update doctors set name_ar = 'د. حسام مليباري', updated_at = now() where slug = 'dr-husam-malibary';
update doctors set name_en = 'Dr. Wafa Alghamdi', updated_at = now() where slug = 'dr-wafa-alghamdi';
update doctors set name_en = 'Dr. Abdulwahab Bawahab', updated_at = now() where slug = 'dr-abdulwahab-bawahab';
update doctors set name_ar = 'د. ساره باداود', updated_at = now() where slug = 'dr-sarah-badawod';
update doctors set name_ar = 'د. وديان ابو زناده', updated_at = now() where slug = 'dr-wedyan-aboznadah';
update doctors set name_en = 'Dr. Yousuf Alqurashi', updated_at = now() where slug = 'dr-yousuf-alqurashi';
update doctors set name_ar = 'د. اسيل الغانمي', updated_at = now() where slug = 'dr-aseel-alghanemi';
update doctors set name_en = 'Prof. Abdullah Alzahrani', updated_at = now() where slug = 'dr-prof-abdullah-alzahrani';
update doctors set name_ar = 'د. احمد الشهراني', updated_at = now() where slug = 'dr-ahmad-alshahrani';
update doctors set name_en = 'Dr. Omar Ashour', name_ar = 'د. عمر عاشور', updated_at = now() where slug = 'dr-omar-ashour';
update doctors set name_ar = 'د. سهيل خوجه', updated_at = now() where slug = 'dr-suhail-khojah';
update doctors set name_en = 'Dr. Salma Omran', updated_at = now() where slug = 'dr-salma-omran';
update doctors set name_en = 'Dr. Abir Albadrani', updated_at = now() where slug = 'dr-abir-al-badrani';
update doctors set name_ar = 'د. اشرف الجحدلي', updated_at = now() where slug = 'dr-ashraf-aljahdali';
update doctors set name_ar = 'د. احمد الجندي', updated_at = now() where slug = 'dr-ahmed-elguindy';
update doctors set name_ar = 'د. اسعد المطوع', updated_at = now() where slug = 'dr-assad-almotowa';
update doctors set name_ar = 'د. رامي سمرقندي', updated_at = now() where slug = 'dr-ramy-samargandi';
update doctors set name_en = 'Dr. Roba Jamalallail', name_ar = 'د. ربى جمل الليل', updated_at = now() where slug = 'dr-roba-jamalallail';
update doctors set name_ar = 'د. فارس الثبيتي', updated_at = now() where slug = 'dr-faris-althubaiti';
update doctors set name_en = 'Dr. Lojain Almadfaa', updated_at = now() where slug = 'dr-lojain-almadfaa';
update doctors set name_ar = 'د. معن ابو زيد', updated_at = now() where slug = 'dr-maan-abuzaid';
update doctors set name_en = 'Dr. Noran Abuouf', name_ar = 'د. نوران ابو عوف', updated_at = now() where slug = 'dr-noran-abuouf';
update doctors set name_ar = 'د. ساره ملايكة', updated_at = now() where slug = 'dr-sarah-malaekah';
update doctors set name_en = 'Dr. Nour Gazzaz', updated_at = now() where slug = 'dr-nour-gazzaz';
update doctors set name_en = 'Dr. Saud Bahaidarah', updated_at = now() where slug = 'dr-saud-bahaidarah';
update doctors set name_ar = 'د. حنين امام', updated_at = now() where slug = 'dr-haneen-imam';
update doctors set name_en = 'Prof. Sami Bahlas', name_ar = 'بروفيسور. سامي بحلس', updated_at = now() where slug = 'dr-prof-sami-bahlas';
update doctors set name_ar = 'د. اكرم بخاري', updated_at = now() where slug = 'dr-akram-bukhari';
update doctors set name_ar = 'د. ماجد سجيني', updated_at = now() where slug = 'dr-majed-sejiny';
update doctors set name_en = 'Dr. Faisla Almuhizi', name_ar = 'د. فيصل المهيزع', updated_at = now() where slug = 'dr-faisal-almuhizi';
update doctors set name_en = 'Dr. Waleed Alhemayed', updated_at = now() where slug = 'dr-waleed-alhemayed';
update doctors set name_ar = 'د. احمد الموسى', updated_at = now() where slug = 'dr-ahmad-almousa';
update doctors set name_en = 'Prof. Turky Almigbal', name_ar = 'بروفيسور. تركي المقبل', updated_at = now() where slug = 'dr-prof-turky-almigbal';
update doctors set name_ar = 'بروفيسور. محمد باتيس', updated_at = now() where slug = 'dr-prof-mohammed-batais';
update doctors set name_ar = 'د. لولوة الاشقر', updated_at = now() where slug = 'dr-lolwah-alashgar';
update doctors set name_en = 'Dr. Majed Albarrak', name_ar = 'د. ماجد البراك', updated_at = now() where slug = 'dr-majed-albarrak';
update doctors set name_en = 'Dr. Abdulrahman Albabtain', updated_at = now() where slug = 'dr-abdulrahman-albabtain';
update doctors set name_ar = 'د. ابراهيم الفواز', updated_at = now() where slug = 'dr-ibrahim-alfawaz';
update doctors set name_ar = 'د. معاذ العمار', updated_at = now() where slug = 'dr-muath-alammar';
update doctors set name_en = 'Dr. Omar Alrahbeeni', updated_at = now() where slug = 'dr-omar-alrahbeeni';
update doctors set name_en = 'Dr. Khalid Alhussaini', updated_at = now() where slug = 'dr-khalid-alhussaini';
update doctors set name_en = 'Dr. Waleed Alhuzaim', name_ar = 'د. وليد الحزيم', updated_at = now() where slug = 'dr-waleed-alhuzaim';
update doctors set name_en = 'Prof. Mohammed Alnaami', name_ar = 'بروفيسور. محمد النعمي', updated_at = now() where slug = 'dr-prof-mohammed-alnaami';
update doctors set name_en = 'Dr. Hashim Ballubaid', updated_at = now() where slug = 'dr-hashim-balubaid';
update doctors set name_ar = 'بروفيسور. عبدالكريم المؤمن', updated_at = now() where slug = 'dr-prof-abdulkareem-almomen';
update doctors set name_ar = 'د. عبدالعزيز السبيعي', updated_at = now() where slug = 'dr-abdulaziz-alsubaie';
update doctors set name_en = 'Dr. Abdulrahman Alqahtani', updated_at = now() where slug = 'dr-abdulrahman-alqahtani';
update doctors set name_ar = 'ساره العيد', updated_at = now() where slug = 'dr-sara-aleid';
update doctors set name_en = 'Dr. Ali Bassi', name_ar = 'د. على باصي', updated_at = now() where slug = 'dr-ali-bassi';
update doctors set name_ar = 'د. بدرية النوح', updated_at = now() where slug = 'dr-badria-alnouh';
update doctors set name_en = 'Dr. Salwa Althagafi', updated_at = now() where slug = 'dr-salwa-al-thagafi';
update doctors set name_en = 'Dr. Samar Altoukhi', updated_at = now() where slug = 'dr-samar-al-toukhi';
update doctors set name_en = 'Dr. Fahad Alruwaily', updated_at = now() where slug = 'dr-fahad-alruwaily';
update doctors set name_en = 'Dr. Abdulaziz Aljohani', name_ar = 'د. عبدالعزيز الجهني', updated_at = now() where slug = 'dr-abdulaziz-aljohani';
update doctors set name_en = 'Dr. Mohammed Aldulaym', name_ar = 'د. محمد الدليم', updated_at = now() where slug = 'dr-mohammed-aldulaym';
update doctors set name_ar = 'بروفيسور. فوزي الجاسر', updated_at = now() where slug = 'dr-prof-fawzi-aljassir';
update doctors set name_en = 'Prof. Abdullah Alshamrani', name_ar = 'د. عبدالله الشمراني', updated_at = now() where slug = 'dr-prof-abdullah-al-shamrani';
update doctors set name_en = 'Prof. Bassam Bin Abbas', name_ar = 'بروفيسور. بسام بن عباس', updated_at = now() where slug = 'dr-prof-bassam-bin-abbas';
update doctors set name_en = 'Dr. Mohammed Alotaibi', name_ar = 'د. محمد العتيبي', updated_at = now() where slug = 'dr-mohammed-alotaibi';
update doctors set name_en = 'Prof. Ahmed Alrumayyan', name_ar = 'بروفيسور. احمد الرميان', updated_at = now() where slug = 'dr-prof-ahmed-al-rumayyan';
update doctors set name_en = 'Prof. Fahad Albashiri', name_ar = 'بروفيسور. فهد البشيري', updated_at = now() where slug = 'dr-prof-fahad-albashiri';
update doctors set name_ar = 'د. احمد الطوب', updated_at = now() where slug = 'dr-ahmed-altoub';
update doctors set name_en = 'Prof. Riyad Al Lehebi', name_ar = 'بروفيسور. رياض اللهيبي', updated_at = now() where slug = 'dr-prof-riyad-al-lehebi';
update doctors set name_ar = 'د. سلمان الصالح', updated_at = now() where slug = 'dr-salman-alsaleh';
update doctors set name_ar = 'د. ايناس حمامة', updated_at = now() where slug = 'dr-enas-hamama';
update doctors set name_ar = 'د. شيماء الشريف', updated_at = now() where slug = 'dr-shaima-alshareef';
update doctors set name_en = 'Dr. Ola Sallam', name_ar = 'د. علا سلام', updated_at = now() where slug = 'dr-ola-sallam';
update doctors set name_ar = 'د. اكرام الشهيدي', updated_at = now() where slug = 'dr-ekram-elshahidy';
update doctors set name_ar = 'د. مروان القصاص', updated_at = now() where slug = 'dr-marwan-elkassas';
update doctors set name_ar = 'د. احمد السيد', updated_at = now() where slug = 'dr-ahmed-alsayed';
update doctors set name_ar = 'د. انمار فطاني', updated_at = now() where slug = 'dr-anmar-fatani';
update doctors set name_ar = 'د. احمد بخش', updated_at = now() where slug = 'dr-ahmad-bakhsh';
update doctors set name_en = 'Dr. Bashair Ali', updated_at = now() where slug = 'dr-bashair-ibrahim';
update doctors set name_ar = 'د. شهد باعارمه', updated_at = now() where slug = 'dr-shahd-baarimah';
update doctors set name_en = 'Dr. Fajr Alsaeedi', name_ar = 'فجر الصعيدي', updated_at = now() where slug = 'dr-fajr-alsaeedi';
update doctors set name_ar = 'د. مروان فلمبان', updated_at = now() where slug = 'dr-marwan-flimban';

-- New doctors from the list (photo: none yet -> site avatar fallback)
insert into doctors (slug, name_en, name_ar, specialty_raw, specialties, branches, cities, is_active, sort_order)
values ('dr-nawaf-alfawzan', 'Dr. Nawaf Alfawzan', 'د. نواف الفوزان', 'Family Medicine', '{"Family Medicine"}'::text[], '{"Al Sahafa"}'::text[], '{Riyadh}'::text[], true,
        (select coalesce(max(sort_order),0)+1 from doctors))
on conflict (slug) do nothing;
insert into doctors (slug, name_en, name_ar, specialty_raw, specialties, branches, cities, is_active, sort_order)
values ('dr-nourhan-jastaniah', 'Dr. Nourhan Jastaniah', 'د. نورهان جستنيه', 'Pediatrics', '{Pediatrics}'::text[], '{"Al Tahlia",Obhour}'::text[], '{Jeddah}'::text[], true,
        (select coalesce(max(sort_order),0)+1 from doctors))
on conflict (slug) do nothing;

-- dr-mirfat-moqbel's image is the generic bamc FemaleDoctor.jpg placeholder;
-- clear it so the site's illustrated avatar fallback applies (like other dentists).
update doctors set image_url = null, updated_at = now()
  where slug = 'dr-mirfat-moqbel' and image_url like 'https://bamc%';

commit;
